Attempted fix of issue #1995
nltk/nltk pull request #2018
Opened 2018-05-14 09:19 UTC by AlokDebnath

The resolution to issue #1995 has been attempted. Please do take a look.

2018-07-26 00:58 UTC, alvations commented on nltk/tokenize/__init__.py
> +_treebank_word_tokenizer.STARTING_QUOTS.append((impoved_open_single_quote_regex, r'\1 \2'))
There's a typo here. It should be:

```python
_treebank_word_tokenizer.STARTING_QUOTES.append((improved_open_single_quote_regex, r'\1 \2'))
```

2018-07-26 00:59 UTC, alvations requested changes
After fixing the typo, it should be as suggested in #1995 , then it would be okay to merge.

2018-08-28 01:41 UTC, alvations submitted a review, later dismissed

2018-08-28 01:42 UTC, alvations commented
Still needs some tests for this. The existing doctest for the tokenizer might break because of the change. Maybe we should add an argument to allow users to choose whether they want to handle clitics.

2018-08-28 02:11 UTC, alvations commented
[CI: retest]

2018-09-18 09:41 UTC, alvations approved these changes
LGTM too!

2018-11-11 21:44 UTC, stevenbird commented
Thanks @AlokDebnath, @alvations

2018-11-11 21:44 UTC, merged