Fixing Witten-Bell
nltk/nltk pull request #2626
Opened 2020-11-21 05:52 UTC by manujosephv

@iliakur 

The Witten-Bell smoothing is a recursive interpolation method, which takes the below form:

![image](https://user-images.githubusercontent.com/10508493/99868793-be99ee00-2beb-11eb-9f69-defbde6c081f.png)

- [Source](http://www.ee.columbia.edu/~stanchen/e6884/labs/lab3/x207.html)
- Page 42 [Source](https://www.statmt.org/book/slides/07-language-models.pdf)
- Page 2[Source](https://www.cl.uni-heidelberg.de/courses/ss15/smt/scribe6.pdf)
- Page 24[Source](https://nlp.stanford.edu/~wcmac/papers/20050421-smoothing-tutorial.pdf)

2020-11-22 22:01 UTC, iliakur requested changes
Just a few very minor points and suggestions.

Regarding the unigram score, I'm not sure we should give up that easy.

I'm gonna have another look at the math again tomorrow, but are you sure the gamma/lambda has been adjusted to fully reflect the adjustment to the unigram probability that you propose?

2020-11-22 22:01 UTC, iliakur commented on nltk/lm/smoothing.py
> +
```suggestion
```

2020-11-22 22:01 UTC, iliakur commented on nltk/test/unit/lm/test_models.py
> +        # 1 word follow ab and ab occured 1 time
```suggestion
        # 1 word follows 'a b' and 'a b' occured 1 time
```
This should make it consistent with 'a b c' on the previous line

2020-11-22 22:01 UTC, iliakur commented on nltk/test/unit/lm/test_models.py
> +        # For unigram scores by default revert to Add-One Smoothed MLE
This isn't strictly true anymore, right?

2020-11-29 15:45 UTC, iliakur commented
@manujosephv Thanks for this. I've double-checked the math for the `gamma` computation once again (better safe than sorry!) and it all checks out.

As far as I'm concerned we can merge this and tackle the unigram issue in a separate PR.

2020-11-29 15:47 UTC, iliakur commented
@manujosephv the failing test is because the WittenBell entropy value has to be adjusted in the doctest. Could you do that?

2020-11-30 04:01 UTC, manujosephv commented
@iliakur  Made the doctest change and other changes..

> @manujosephv the failing test is because the WittenBell entropy value has to be adjusted in the doctest. Could you do that?

2020-12-12 07:42 UTC, iliakur commented
Ok, this lgtm!

We can deal with unigram probabilities in a separate MR.

2020-12-12 20:55 UTC, merged

2020-12-12 20:56 UTC, stevenbird commented
Thanks @manujosephv and @iliakur!