Allowed properties overloading for CoreNLPParser tag, Authors.md
nltk/nltk pull request #2789
Opened 2021-08-29 12:27 UTC by BatMrE

Added the overloading properties in code as per the standards,

getting results as expected:
`[('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111', 'DATE'), ('1111', 'DATE'), ('1111', 'DATE')]`

2021-08-30 08:06 UTC, tomaarsen commented
For those interested in the reasoning behind the changes in this PR, feel free to have a look at #2112 itself, where all the changes are already described and laid out.

2021-08-31 00:21 UTC, dimazest commented on nltk/parse/corenlp.py
> +        if properties is None:
Please add a description for the `properties` argument in the docstring, also mention that `"tokenize.whitespace"` is set to `True` by default (but it won't if `properties` are specified.

2021-08-31 00:22 UTC, dimazest commented
> before fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111\xa01111\xa01111', 'O')]
after fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111', 'DATE'), ('1111', 'DATE'), ('1111', 'DATE')]
would it be possible to make a test out of this example?

2021-09-02 12:41 UTC, BatMrE commented
> > before fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111\xa01111\xa01111', 'O')]
> > after fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111', 'DATE'), ('1111', 'DATE'), ('1111', 'DATE')]
> 
> would it be possible to make a test out of this example?

Sure , bit busy, will add over weekend

2021-09-05 17:52 UTC, BatMrE commented
> > before fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111\xa01111\xa01111', 'O')]
> > after fix : [('my', 'O'), ('phone', 'O'), ('number', 'O'), ('is', 'O'), ('1111', 'DATE'), ('1111', 'DATE'), ('1111', 'DATE')]
> 
> would it be possible to make a test out of this example?

@tomaarsen @dimazest  
any idea how to create 'api_return_value' dictionary for a sample?? like in:
https://github.com/nltk/nltk/blob/develop/nltk/test/unit/test_corenlp.py#L261

2021-09-07 19:10 UTC, dimazest commented
you should be able to manually use CoreNLP Rest API and intercept returned result

2021-09-07 20:09 UTC, tomaarsen commented
Keep in mind that the CoreNLP tests are being skipped, because our GitHub Actions CI doesn't currently support downloading third party tools such as the Stanford models. Preferably we would still have tests for this PR though, as we likely want to support third party tools eventually.

2021-09-07 20:11 UTC, dimazest commented
The actual call to corenlp should be mock, then tests won't need corenlp running.

2021-10-12 09:10 UTC, tomaarsen commented
Since #2820 there are automated tests for CoreNLP. We would like to see some tests to back up these changes, is possible.

2021-10-26 12:23 UTC, tomaarsen requested changes

2021-10-26 12:23 UTC, tomaarsen commented on nltk/parse/corenlp.py
> +            properties = {"tokenize.whitespace": "true"}
I've merged develop into this PR. Because the CoreNLP tests now run on the CI, we can see that some tests fail due to this change.

2021-11-28 06:36 UTC, BatMrE commented on nltk/parse/corenlp.py
> +            properties = {"tokenize.whitespace": "true"}
@tomaarsen apart from automated tests for CoreNLP is there any other test that needs to be added

2021-11-28 14:23 UTC, tomaarsen commented on nltk/parse/corenlp.py
> +            properties = {"tokenize.whitespace": "true"}
The PR should have some tests that show that the new behaviour works like intended, so you would only need to add tests for the functionality that you added. So, just for these functions.

2022-07-05 12:30 UTC, stevenbird commented
@BatMrE: just wondering if there's interest in wrapping this up. I think it's just a question of adding a test or two.

2025-03-10 10:31 UTC, stevenbird commented
Closing. Hopefully someone will resurrect this if it's still an issue.

2025-03-10 10:31 UTC, closed without merging