Deprecate 'return_str' parameter in NLTKWordTokenizer and TreebankWordTokenizer
nltk/nltk pull request #2883
Opened 2021-11-10 19:20 UTC by adamjhawley

Resolves #2879 

As per the discussion on #2879, I have deprecated the use of the 'return_str' parameter in the `tokenize` method of both `NLTKWordTokenizer` and `TreebankWordTokenizer`.

I have currently done this in a way that raises a `DeprecationWarning` if a non-default value is passed to the parameter.

2021-11-10 21:46 UTC, tomaarsen requested changes
I have two small comments on your work. Beyond that, looks great!

Eventually we'll want the deprecation of `return_str` to be described in the method documentation, but the PR for that documentation is still open: #2878. That's something for when both this and that PR are merged (or at least one of the two).

2021-11-10 21:46 UTC, tomaarsen commented on nltk/tokenize/destructive.py
> +                "longer be used.",
```suggestion
                "Parameter 'return_str' has been deprecated and should no "
                "longer be used.",
```
This string will be concatenated with no space between `no` and `longer`.

2021-11-10 21:46 UTC, tomaarsen commented on nltk/tokenize/treebank.py
> +                "longer be used.",
```suggestion
                "Parameter 'return_str' has been deprecated and should no "
                "longer be used.",
```
idem.

2021-11-10 22:41 UTC, adamjhawley commented
@tomaarsen thanks for the review! I have amended the commit to contain your suggestions

2021-11-11 06:28 UTC, tomaarsen approved these changes
Looks good to me! Thank you.
I'll leave this open for a little bit so others can have a look at it.

2021-11-12 13:25 UTC, stevenbird approved these changes

2021-11-15 09:30 UTC, 12mohaned commented
I have a nit comment, I would suggest refactoring the if's in Treebank and WordTokenizer to be:

```
if return_str:
  ..........
```

instead of

```
if return_str is not False:
  ..........
```

It is more readable and faster. Also, it is more pythonic and follows the PEP8 standard.

2021-11-15 11:28 UTC, tomaarsen commented on nltk/tokenize/destructive.py
> +        if return_str is not False:
```suggestion
        if return_str:
```
Well spotted @12mohaned! This is also more in line with the old behaviour of `text if return_str else text.split()`.

2021-11-18 12:54 UTC, merged

2021-11-18 12:55 UTC, stevenbird commented
Thanks @adamjhawley, @12mohaned, @tomaarsen