Add extended open multilingual wordnet reader
nltk/nltk pull request #2924
Opened 2021-12-22 04:04 UTC by ExplorerFreda

Related NLTK data issue: https://github.com/nltk/nltk_data/issues/179
Extended open multilingual wordnet: http://compling.hss.ntu.edu.sg/omw/summx.html

2021-12-23 10:57 UTC, tomaarsen commented
Hey! We use [`pre-commit`](https://pre-commit.com/) hooks to ensure code quality through our [`pre-commit config`](https://github.com/nltk/nltk/blob/develop/.pre-commit-config.yaml), which runs `pyupgrade`, `black`, `isort` and some other hooks. Using it is as simple as `pip install pre-commit` and then running `pre-commit install`. From then onwards, any time you commit to `https://github.com/ExplorerFreda/nltk`, it will run these hooks before committing. 
The first time you might not have any changes to turn into a commit, so you can do `pre-commit run --all` or try to create an empty commit, and it will format your changes. You can then push this to make the CI stop complaining.

2021-12-23 11:19 UTC, tomaarsen requested changes
I recognise that this is a bit of an annoying situation, because any (automated) tests will fail due to `extended_omw` not yet existing in `nltk_data`, but perhaps you can provide a bit of sample code that should work if we (manually) download `extended_omw` and place it in our `nltk_data` folder?

Beyond that I added some small nitpicks. I can't really comment on the "real functionality", because I haven't been able to run it.

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +from IPython.core.pylabtools import configure_inline_support
This seems like an unused import. Should this be there?

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +from traitlets.traitlets import default
This seems like an unused import. Should this be there?

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +# Natural Language Toolkit: Extened Open Multilingual WordNet Reader
```suggestion
# Natural Language Toolkit: Extended Open Multilingual WordNet Reader
```

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +                fp.close()
The `with` keyword already automatically closes any files whenever the `with` scope is exited, so this line is unnecessary.

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +                fp.close()
Idem.

2021-12-23 11:19 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +        """prevent synsets from mistakenly added"""
Is this missing "being"?

2021-12-24 07:27 UTC, ExplorerFreda commented
> I recognise that this is a bit of an annoying situation, because any (automated) tests will fail due to `extended_omw` not yet existing in `nltk_data`, but perhaps you can provide a bit of sample code that should work if we (manually) download `extended_omw` and place it in our `nltk_data` folder?
> 
> Beyond that I added some small nitpicks. I can't really comment on the "real functionality", because I haven't been able to run it.

Hi @tomaarsen, thanks for the review and suggestions! I've changed the code correspondingly. 

Below is the script for downloading the required data that should work: 
```bash
cd $NLTK_DATA_DIR/corpora/
wget http://compling.hss.ntu.edu.sg/omw/wn-wikt.zip -O extended_omw.zip
unzip extended_omw.zip
mv data/ extended_omw/
```

2021-12-24 13:42 UTC, tomaarsen commented on nltk/corpus/reader/extended_omw.py
> +# Natural Language Toolkit: Exteneded Open Multilingual WordNet Reader
```suggestion
# Natural Language Toolkit: Extended Open Multilingual WordNet Reader
```
I haven't had the time to take a full look at this PR yet, but I noticed this small typo.

2022-02-10 12:46 UTC, ekaf commented
It would be nice to add the following capabilities:

1. Loading the English wiktionary wordnet. This requires small modifications in the wordnet module because it does not anticipate English wordnets from alternative provenances at this moment.

2. Loading different wordnets for the same language separetely would allow to compare the quality of different provenances. The reason why the 'wikt' and 'cldr' provenances did not go into the official OMW 1.4 package was that their quality was deemed uncertain. For each language, this PR uses the set union of all provenances, which may be appropriate for some uses, but it would be nice to also support different use cases.

3. Combining extended_wordnet with newer wordnet packages like wordnet31 and wordnet2021. This would be easier if the extended_omw corpus reader was a leaner class, that could be added to any English Wordnet, including the forthcoming ones like Open English Wordnet 2022.

4. For completeness, maybe also consider adding back the Persian wordnet and the alternative Chinese wordnet from the old OMW package (in the 'pas' and 'qcn' directories), which were left out of OMW 1.4 for quality reasons though it is possible that some users miss them.

2022-03-01 23:44 UTC, stevenbird commented
Resolved in #2946

2022-03-01 23:45 UTC, stevenbird commented
@ExplorerFreda thanks for your work, which is appreciated even though we ended up accepting a different PR.

2022-03-01 23:45 UTC, closed without merging