Fix wordnet's all_synsets() function
nltk/nltk pull request #3078
Opened 2022-12-01 15:15 UTC by ekaf

Fix #3077, and a few related problems in wordnet.py.

1. With the English Wordnet, properly distinguish satellites from adjectives:

```
from nltk.corpus import wordnet as wn
print(wn.get_version())
```
3.0

`print(len(list(wn.all_synsets(pos="a"))))`
18156

`print(len(list(wn.all_synsets(pos="s"))))`
10693

2. With other languages, a part of the problem is due to the _synset_from_pos_and_offset()_ function, which returns an empty synset object when an offset is incorrect. This leads to inflated synset counts with OMW for two reasons: OMW does include some incorrect offsets, and with later wordnets some synsets that are lost in mapping should not be counted. So, when a synset does not exist, this PR returns _None_ instead of an empty synset object:

```
ss = wn.synset_from_pos_and_offset('n',1234)
print(ss)
```
None

```
wn.add_omw()
print(len(list(wn.all_synsets(lang="hrv"))))
```
23115
`print(len(list(wn.all_synsets(pos="n", lang="hrv"))))`
16177
`print(len(list(wn.all_synsets(pos="v", lang="hrv"))))`
4736

Another problem is that the handling of satellites in the mappings was inconsistent. The mapping procedure has now been rewritten in a style that makes it easier to follow the underlying algorithm.

```
from nltk.corpus import wordnet31 as wn31
print(wn31.get_version())
```
3.1
```
wn31.add_omw()
print(len(list(wn31.all_synsets(lang="hrv"))))
```
23098
`print(len(list(wn31.all_synsets(pos="a", lang="hrv"))))`
1363
`print(len(list(wn31.all_synsets(pos="s", lang="hrv"))))`
444

2022-12-06 12:31 UTC, tomaarsen requested changes
I've added some simple tests. I also accidentally brought in 2f34b52 into this PR, so I rebased and removed some of the unnecessary commits. Apologies for this. Make sure to update locally to avoid issues if you make changes!

I had some comments and requests for changes. I hope you'll be able to have a look at them.

2022-12-06 12:31 UTC, tomaarsen commented on nltk/corpus/reader/wordnet.py
> +    def indexSense(self, version=None):
```suggestion
    def index_sense(self, version=None):
```
Could we stick with snake case method names, as suggested by the Python [style guide](https://peps.python.org/pep-0008/#method-names-and-instance-variables). Optionally, we can use a single underscore in front of a method name if it's not meant to be used by the public. This may be the case for e.g. `mapToMany`?

2022-12-06 12:31 UTC, tomaarsen commented on nltk/corpus/reader/wordnet.py
> +    def mapToMany(self):
```suggestion
    def map_to_many(self):
```
Idem. I'd rather also see snake casing for the variables.

2022-12-06 12:31 UTC, tomaarsen commented on nltk/corpus/reader/wordnet.py
> +    def mapToOne(self):
```suggestion
    def map_to_one(self):
```
Idem. I'd rather also see snake casing for the variables.

2022-12-06 12:31 UTC, tomaarsen commented on nltk/corpus/reader/wordnet.py
> +
Is this meant as a public method, or is it just a leftover method that is now no longer used?

2022-12-06 12:31 UTC, tomaarsen commented on nltk/corpus/reader/wordnet.py
> +
Also, the commented line can be removed.

2022-12-07 08:56 UTC, ekaf commented on nltk/corpus/reader/wordnet.py
> +    def indexSense(self, version=None):
Thanks @tomaarsen, I have added all your suggestions for the function names, and also changed the variable names.

2022-12-07 09:01 UTC, ekaf commented on nltk/corpus/reader/wordnet.py
> +    def mapToMany(self):
Fixed, I also did the same with variable names. Thanks @tomaarsen!

2022-12-07 10:01 UTC, tomaarsen approved these changes
This is looking good! Thanks for always helping maintain Wordnet in NLTK!

2022-12-07 10:02 UTC, merged