Naissue 3189
nltk/nltk pull request #3224
Opened 2023-12-27 19:49 UTC by Higgs32584

With this pull request, I hope to fix the issue of #3189, or the word_tokenize() Failed to Split English Contractions When Followed by [\t\n\f\r]. 

Obviously this is the first draft, but I would like some initial review and comments. Thank you

2023-12-27 20:25 UTC, Higgs32584 commented
#3189

2023-12-29 17:28 UTC, Higgs32584 commented
@stevenbird Hi, I was wondering what you thought about this? The issue that I hope to fix here is the problem with word_tokenize() Failing to Split English Contractions When Followed by [\t\n\f\r] The solution I came up with was removing \t\n\f\r from the sentence.

In terms of unintended side effects, I would not expect this to cause issue due to the fact that a space would replace the tab. 


I can add some tests to verify the fix, although first, I was wondering if you would be interested in merging it? Thank you?

2024-01-18 15:45 UTC, Higgs32584 commented
@purificant can I get a review of this? I think it is solid and ready for merging. Thank you

2024-01-21 08:49 UTC, ekaf commented
This doesn't solve the full problem: _word_tokenize_ would still fail to split contractions followed by [\a\b\v]. So the first step would be trying to find the extent of the problem.
Concerning the implementation, there is no point in making the same substitution in both STARTING_QUOTE and END_QUOTE:
after the substitution has been applied once, there is nothing left to substitute in the second round.
The ideal reviewers for this PR would be the authors of the _destructive.py_ file (@alvations and @tomaarsen ). But there is no hurry, as long as this work is far from mergeable in its present state.

2024-01-21 15:48 UTC, Higgs32584 commented
@ekaf thank you for figuring out the full problem scope. I was unaware of the other parts of this.

Regarding the STARTING QUOTE and the END QUOTE part. I will have to look, but I believe the bug failed to be resolved unless I had the substitution present in both places. I would not add more lines of code than needed :)

2024-01-21 16:39 UTC, ekaf commented
@Higgs32584, I don't know the full problem scope, there could be more... Neither do I know the best place to do the substitution, but I have verified that it works when listing it only under STARTING_QUOTE. Having it only under PUNCTUATION also works.

2024-02-04 12:22 UTC, ekaf commented
The cause of the problem is that the two last lines under ENDING_QUOTE are handling contractions, using a regular expression that requires the contraction to be followed by a plain space. So the match fails when the contraction is followed by some other escaped whitespace-like character. 
The problem can be solved by converting all whitespace escape sequences to a single plain space,  for ex. with the following substitution pair: 

`
(re.compile(r"\s+"), " "),
`

This substitution can probably be applied anywhere _before_ the two last substitutions in ENDING_QUOTE, and I suppose it wouldn't
hurt to apply it early.

2024-02-04 12:28 UTC, ekaf requested changes
It is redundant to apply the same substitution twice.

The following substitution handles more white-space like characters:
`
 (re.compile(r"\s+"), " "),
`
It should be applied _before_ the two last substitutions in ENDING_QUOTE, which are causing the problem.

2024-02-04 15:37 UTC, Higgs32584 commented
@ekaf Thank you for the suggestions. Do you need some test cases as well? I know some repos want test cases added with every bug fix.

2024-02-04 16:30 UTC, ekaf commented
Thanks @Higgs32584, this looks good. Test cases are always much appreciated everywhere.

2024-02-04 16:34 UTC, ekaf approved these changes

2024-02-04 16:37 UTC, ekaf approved these changes
I think this solves #3189.

2024-07-08 22:19 UTC, alvations commented on nltk/tokenize/destructive.py
> +        (re.compile(r"\s+"), " "),
This will compress the continuous whitespaces of different types into one. 

Note: `\s` = `[\r\n\t\f\v ]`

2024-07-08 22:19 UTC, alvations approved these changes
LGTM! Thanks for the fix!

2024-07-08 22:37 UTC, merged