Add reference to entropy implementation used
nltk/nltk pull request #3229
Opened 2024-01-26 14:59 UTC by mbauwens

This is in reference to issue #2961.

This is just a simple addition to the [docs](https://www.nltk.org/api/nltk.lm.api.html#nltk.lm.api.LanguageModel.entropy), making it more clear that the entropy implementation in NLTK is the one based on the Shannon-McMillan-Breiman theorem, as used and referenced by Jurafsky ([Chapter 3 page 23 - 3.49](https://web.stanford.edu/~jurafsky/slp3/3.pdf)) and Jordan Boyd-Graber (`lm.txt` file in [this comment](https://github.com/nltk/nltk/issues/1342#issuecomment-203060085)).

This PR does not include the alternative implementation of the entropy function that was proposed in the issue.

2024-01-26 15:29 UTC, iliakur requested changes
Minor nits, otherwise lgtm, thanks!

2024-01-26 15:29 UTC, iliakur commented on nltk/lm/api.py
> +        as used and referenced by Jurafsky and Jordan Boyd-Graber.
```suggestion
        as used and referenced by Dan Jurafsky and Jordan Boyd-Graber.
```
Consistently use full names

2024-01-26 15:29 UTC, iliakur commented on nltk/lm/api.py
> +        This implementation is based on the Shannon-McMillan-Breiman theorem,
```suggestion

        This implementation is based on the Shannon-McMillan-Breiman theorem,
```
Just to stay consistent with other docstrings in the module

2024-01-26 16:35 UTC, mbauwens reviewed
Minor changes in formatting of text

2024-01-26 18:15 UTC, iliakur commented on nltk/lm/api.py
> +    def entropy_extended(self, text_ngrams, text_fdist, length_normalisation=True, rel_freq_weighting=False):
Oh, hmm, I think I'll have to review this properly I'm afraid.

One thing that worries me is lack of tests. Let's maybe do it in a separate PR, I can help you with that.

2024-01-26 19:00 UTC, mbauwens commented on nltk/lm/api.py
> +    def entropy_extended(self, text_ngrams, text_fdist, length_normalisation=True, rel_freq_weighting=False):
@iliakur oh, my bad! I did not intend to already add these changes to the PR. I'm new to making PRs and didn't realise an updated fork would also be reflected into the previous PR. Will remove this from the PR!

2024-01-26 19:12 UTC, mbauwens commented
@iliakur yeah, so a bit messy here, but I've reverted the PR to just the update to the docs. I now have a separate branch on my fork that I'll be getting ready for a PR for an alternative entropy/perplexity method, including tests :)

2024-01-27 13:59 UTC, iliakur approved these changes

2024-01-27 14:01 UTC, iliakur commented
@stevenbird @tomaarsen this PR is ready to merge. I've been away from nltk development long enough that I figured I'd check in with you two about any formalities that may be missing.

2024-01-29 09:04 UTC, tomaarsen commented
I'm afraid I've also not had much time for NLTK recently. That said, I think this is good to go. Thanks for taking care of this, and nice to see you here again @mbauwens.

- Tom Aarsen

2024-01-29 09:04 UTC, merged