Write downloaded model files atomically
nltk/nltk pull request #3247
Opened 2024-04-19 08:49 UTC by naktinis

Avoiding scenarios where one processes may be reading a file that is being written by another one by only moving the file to the final location after it has been fully written.

2024-04-19 17:01 UTC, ekaf commented
@naktinis, does this PR solve a currently known problem? In particular, it would be great to know if it solves any of the many many open issues concerning NLTK download errors.

2024-04-19 17:23 UTC, naktinis commented
@ekaf this is an attempt to solve an issue we are having despite installing directly from `develop` branch (which already includes this unreleased fix: https://github.com/nltk/nltk/commit/69635b464f2adfa56e4f2ba2db7e2a72d11ac1ba).

The error we get almost every time is `Error with downloaded zip file`.

Our scenario is that we launch multiple processes simultaneously in an environment where there are no models downloaded yet.

So it appears the following sequence is quite likely in such circumstances (and my guess is that it's causing our error):
1. process A checks if the model is downloaded – it is not, so clears the file and starts the download
2. process B checks if the model is downloaded – it still is not, so clears the file and starts the download too
3. process A finishes the download
4. process A opens the model file – but process B is writing to it
5. process A tries reading the content of the model file and fails because it is not fully downloaded

2024-04-19 17:24 UTC, naktinis commented
I couldn't see any directly related issues currenlty reported, but if you have any that seem relevant, I'm happy to take a look. I can also report this issue separately to have it associated with this PR if that's helpful.

2024-04-19 19:24 UTC, ekaf commented
There have been many issues related to downloading and zip files.
Searching for "download" in issues yields [this long list](https://github.com/nltk/nltk/issues?q=is%3Aissue+download+). Most are closed, but problems keep returning, so it would be really great if your solution fixed something already seen.
Otherwise, please open a new issue to describe your specific problem.

2024-05-06 17:51 UTC, naktinis commented
@ekaf I went through all open issues mentioning "download" and couldn't find anything obviously matching this, so I created an issue that includes a script to reproduce this: https://github.com/nltk/nltk/issues/3248.

2024-05-07 09:17 UTC, ekaf commented
Thanks @naktinis for the issue and the test script.  Your scenario seems plausible, because the NLTK downloader dates back to a time where running multiple parallel processes was less common than now.

But given the large numbers of users who have had problems with downloading NLTK data packages, it seems surprising that none of them had similar errors. This would mean that you are downloading in a different way from everybody else, and I wonder what that could be? 

Hopefully, some users with download problems will try your solution, and see if it works for them.

2024-05-17 07:59 UTC, ekaf requested changes
Before initiating any download, the downloader already tests for the existence of the destination file (L690-L696), and mistakingly raises the STALE status when meeting the race condition. A better handling of this situation could  avoid useless multiple downloads of the same file.

2024-09-28 14:54 UTC, ekaf commented
Here's a completely untested suggestion by Copilot. The proposed lock seems reasonable, so given the severity of the problem, it might be worthwile to consider:

To prevent downloading multiple copies of the same file in parallel, you can use a lock mechanism. Here is a suggested modification to the `nltk/downloader.py` file:

```python
import threading
download_locks = {}

class Downloader:
    # Other methods...

    def _download_package(self, info, download_dir, force):
        lock = download_locks.setdefault(info.id, threading.Lock())
        if not lock.acquire(blocking=False):
            yield ErrorMessage(info, f"Download of {info.id} is already in progress.")
            return

        try:
            yield StartPackageMessage(info)
            yield ProgressMessage(0)

            # Do we already have the current version?
            status = self.status(info, download_dir)
            if not force and status == self.INSTALLED:
                yield UpToDateMessage(info)
                yield ProgressMessage(100)
                yield FinishPackageMessage(info)
                return

            # Remove the package from our status cache
            self._status_cache.pop(info.id, None)

            # Check for (and remove) any old/stale version.
            filepath = os.path.join(download_dir, info.filename)
            if os.path.exists(filepath):
                if status == self.STALE:
                    yield StaleMessage(info)
                os.remove(filepath)

            # Ensure the download_dir exists
            os.makedirs(download_dir, exist_ok=True)
            os.makedirs(os.path.join(download_dir, info.subdir), exist_ok=True)

            # Download the file.  This will raise an IOError if the url
            # is not found.
            yield StartDownloadMessage(info)
            yield ProgressMessage(5)
            try:
                infile = urlopen(info.url)
                with open(filepath, "wb") as outfile:
                    num_blocks = max(1, info.size / (1024 * 16))
                    for block in itertools.count():
                        s = infile.read(1024 * 16)  # 16k blocks.
                        outfile.write(s)
                        if not s:
                            break
                        if block % 2 == 0:  # how often?
                            yield ProgressMessage(min(80, 5 + 75 * (block / num_blocks)))
                infile.close()
            except OSError as e:
                yield ErrorMessage(
                    info,
                    "Error downloading %r from <%s>:" "\n  %s" % (info.id, info.url, e),
                )
                return
            yield FinishDownloadMessage(info)
            yield ProgressMessage(80)

            # If it's a zipfile, uncompress it.
            if info.filename.endswith(".zip"):
                zipdir = os.path.join(download_dir, info.subdir)
                # Unzip if we're unzipping by default; *or* if it's already
                # been unzipped (presumably a previous version).
                if info.unzip or os.path.exists(os.path.join(zipdir, info.id)):
                    yield StartUnzipMessage(info)
                    for msg in _unzip_iter(filepath, zipdir, verbose=False):
                        # Somewhat of a hack, but we need a proper package reference
                        msg.package = info
                        yield msg
                    yield FinishUnzipMessage(info)

            yield FinishPackageMessage(info)
        finally:
            lock.release()
            del download_locks[info.id]
```

This code uses a dictionary of locks to ensure that each file is only downloaded once at a time, preventing duplicate parallel downloads.k

2024-09-30 11:01 UTC, ekaf commented
@naktinis, sorry for my now deleted suggestion by Copilot about a lock mechanism. It proved useless, and further dialog with Copilot was frustrating and a complete waste of time.

2024-10-01 07:56 UTC, naktinis commented
Once this logic is in place (ensuring atomic file moves), we could guarantee that the file in the final destination is written after complete download (and not some interrupdated half-download). Then we could have an `if os.path.isfile(model_path)` could give better guarantees that we don't need to retry the download.

The only theoretical issue would be if that complete download got corrupted in transit (network or disk errors), but then we could use the `force=True` or on this hopefully rare scenario simply clean up the model and retry.

Finally, if we want to avoid double downloads (if we start a service with multiple nltk processes that all try to download), we could introduce locks on the temporary file. We'd probably need some platform independent library like https://pypi.org/project/filelock/ (haven't tried this myself yet, only linux flock).

2024-10-01 08:17 UTC, ekaf commented
The real problem is to avoid multiple useless downloads of the same file, because script kids can use this vulnerability to launch a distributed attack on the download servers. 
Writing files atomically makes the problem worse, because it would be preferable that these useless downloads fail. So I am completeletely opposed to your solution, and would personally reject it. Maybe other NLTK developers have a different viewpoint though.

2024-10-01 09:12 UTC, naktinis commented
What I tried to explain in my comment above is that atomic writing can go together with locking. It would work like this:
1. try to obtain a lock on `/model-dir/model.tmp`
2. if the lock can not be obtained, wait for the lock to expire (after we eventually get the lock, check if the final target already has the file - meaning another process properly downloaded it there)
3. if the lock can be obtained (assuming the final target does not exist yet), download to `/model-dir/model.tmp`
4. when the download finishes atomically move `/model-dir/model.tmp` to `/model-dir/model`

If for some reason thousands of concurrent workers are launched, step 2 should prevent simultaneous downloads.

2024-10-01 11:40 UTC, ekaf commented
Thanks @naktinis. Yes, I agree that once a working lock is in place to prevent useless multiple downloads, then writing files atomically could be a nice complement. But the first goal is to ensure that users only download any package once. 
I have tried various approaches to locking, but none that worked across multiple Processes or threads.

2024-10-01 11:54 UTC, naktinis commented
Have you tried https://pypi.org/project/filelock/ yet?

Documentation:
https://py-filelock.readthedocs.io/en/latest/

Example (should work across processes; they even have a video demo in the documentation page):
```
from filelock import Timeout, FileLock

lock = FileLock("high_ground.txt.lock")
with lock:
    with open("high_ground.txt", "a") as f:
        f.write("You were the chosen one.")
```

Btw, I'm guessing it's fine to have the lock on the `tmp` file itself and we probably don't need an extra `.lock` file. As long as the `tmp` file name is shared across processes (and not uniquely generated by each process).

2024-10-02 11:42 UTC, ekaf commented
Thanks @naktinis, but I prefer not to add yet another dependency. Python already has an RLock mechanism that solves #3248,
When you only download each file once, there is no race condition. Then I'm not sure that writing files atomically has any utility.

2024-10-02 11:43 UTC, ekaf commented
Thanks @naktinis, but I prefer not to add yet another dependency. Python already has an RLock mechanism that solves #3248,
When you only download each file once, there is no race condition. Then I'm not sure that writing files atomically has any utility.

2024-10-03 12:46 UTC, ekaf commented
@naktinis, now #3327 uses a multiprocessing Manager dictionary of booleans to emulate locks. Would you consider that, to prevent your race conditions?

2024-10-03 13:34 UTC, naktinis commented
We had to stop using `nltk` in production. However, if the locking prevents failures with the test script here https://github.com/nltk/nltk/issues/3248 (assuming you can reproduce the failure with the code version before the fix), then it should be fine.

2024-10-05 08:24 UTC, ekaf commented
@naktinis, in the current NLTK version 3.9.1, the tokenizer no longer uses pickles, so the data package to download is now _punkt_tab_.

So your test script in #3248 first needs to be updated to download punkt_tab instead of punkt.

But even then, without a fix, race conditions cause a variable number of LookupErrors. 

After PR #3327 however, there is no race condition because the package is only downloaded once.

2024-10-05 10:14 UTC, naktinis commented
Great! Then I guess the only other case is if the downloading processes are not launched with `multiprocessing` from the same parent process but independently from the operating system. But if this already solves a class of problems, then may be good to go.

2024-10-05 10:50 UTC, ekaf commented
Thanks @naktinis! Indeed, in case the parallel processes are launched directly from the OS, it would be safer to write the files atomically.  Or maybe some robust filelock can be implemented.

2026-04-04 12:16 UTC, ekaf commented
Superseded by #3549?

2026-05-04 09:07 UTC, ekaf commented
After #3549 was merged, #3248 should no longer occur. Still, it makes sense to write files atomically, but then this PR would need to resolve its conflicts and address the review suggestions. Otherwise it seems stale and could be closed.

2026-05-12 04:29 UTC, closed without merging